[package]
name = "slate-framework"
description = "GPU-accelerated Rust UI framework — umbrella crate"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
slate-platform = { path = "../slate-platform", version = "0.0.1" }
slate-renderer = { path = "../slate-renderer", version = "0.0.1" }
